version: '3.7'
name: multi-camera-server

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 100ms
      timeout: 5s
      retries: 3000 # 5 minutes
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: mysecretpassword
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9090:9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3
  camera-server:
    image: multi-camera-system
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "src/server_main.py"]
    volumes:
      - ./:/app:ro
    environment:
      DB_CONNECTION: "postgres://postgres:mysecretpassword@postgres:5432/camera_db"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - minio
  camera-camera:
    image: multi-camera-system
    command: ["python", "src/camera_main.py", "--dummy-mode", "True"]
    environment:
      DB_CONNECTION: "postgres://postgres:mysecretpassword@postgres:5432/camera_db"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      camera-server:
        condition: service_started
volumes:
  postgres_data:
  minio_data: